[package]
name = "mclang-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mclang-common = {path = "../mclang-common"}

parse_int = {workspace = true}